# Analysis

In [1]:
import pandas as pd
import numpy as np
import os

## Global Variables

In [2]:
ARGS = {
    "aodmodIN_path": "dataset/extract/AOD_DATA/datas/MOD04/IN/",
    "aodmodET_path": "dataset/extract/AOD_DATA/datas/MOD04/ET/",
    "aodmodUS_path": "dataset/extract/AOD_DATA/datas/MOD04/US/",
    "aodmydIN_path": "dataset/extract/AOD_DATA/datas/MYD04/IN/",
    "aodmydET_path": "dataset/extract/AOD_DATA/datas/MYD04/ET/",
    "aodmydUS_path": "dataset/extract/AOD_DATA/datas/MYD04/US/",
    "aod_header": "dataset/extract/AOD_DATA/header.csv",
    "merra2_path": "dataset/extract/MERRA2/",
    "rmd_path": "dataset/extract/Reference_Monitor_Data/",
    "aqs_path": "dataset/extract/AirQualitySystem.csv",
}

## Dataframes

__AOD_DATA__:

- satellite-derived Aerosol Optical Depth (AOD)
- number of lines corresponding to best quality measurement days
- February 2000 for MODIS-Terra and from July 2002 for MODIS-Aqua through April 2019
- Each measurement line includes the AOD for the 10km x 10 km grid point closest to the ground site as well as the average and standard deviation for 3×3 grid points centered on the closest grid point
- The data file names are: 'Country_City_Location.ProductName.csv'
- The Product Name:
	- MYD04 : This represents MODIS-AQUA satellite (Afternoon overpass)
 	- MOD04 : This represents MODIS-TERRA satellite (Morning overpass)
- The data order in each file
	- YYYY, MM, DD, Latitude, Longitude, AOD1, AOD3, STD3
  - Where
    - AOD1: Aerosol Optical Depth at 550 nm for nearest grid to ground location
 	- AOD3: Aerosol Optical Depth at 550 nm, averaged for 3x3 grids around ground location
	- STD3: Standard Deviation in AOD3 
- Aerosol Optical Depth is a unitless quantity
- The data are extracted from MODIS deep blue and Dark Target algorithm and combined using best quality flags
- The valid AOD range is -0.05 to 5.0
- The missing data are filled with value of -1.0   
- files
  - “station_for_state” is the list of 22 sites selected for the sample data set
  - “readme_csv_sat” provides details on the AOD files

In [ ]:
# Headers
aod_header = pd.read_csv(ARGS["aod_header"], header=None).iloc[0]
aod_header[len(aod_header)] = "Undefined"
aod_header

In [ ]:
# Dataframe
df_aodmod = pd.concat(
    [pd.read_csv(
        ARGS["aodmodUS_path"] + _,
        names=aod_header,
        header=None,
        usecols=aod_header[:-1]
    ) for _ in os.listdir(ARGS["aodmodUS_path"])],
    ignore_index=True
)
df_aodmod.head()

In [ ]:
# Dataframe
df_aodmyd = pd.concat(
    [pd.read_csv(
        ARGS["aodmydUS_path"] + _,
        names=aod_header,
        header=None,
        usecols=aod_header[:-1]
    ) for _ in os.listdir(ARGS["aodmydUS_path"])],
    ignore_index=True
)
df_aodmyd.head()

__MERRA2__:

- Within each file are 24 hourly measurements for each of the 22 station locations
- Fields
  - Station – Name of ground monitor for data row
  - Lat – Latitude (degrees north) of station
  - Lon – Longitude (degrees east) of station
  - SRadius – Search radius (km) for nearest MERRA grid point to station
  - MERRALat – Latitude (degrees north) of nearest MERRA grid point to station
  - MERRAlon – Longitude (degrees east) of nearest MERRA grid point to station
  - IDXi – I index of MERRA grid point
  - IDXj – J index of MERRA grid point
  - PS – Surface pressure (Pa)
  - QV10m – Specific humidity at 10 m above surface (kg/kg)   	(multiplied by 1000.0)
  - Q500 - Specific humidity at 500 mbar pressure (kg/kg) 		(multiplied by 1000.0)
  - Q850 – Specific humidity at 850 mbar pressure (kg/kg) 		(multiplied by 1000.0)
  - T10m – Temperature at 10 m above surface (Kelvin)
  - T500 – Temperature at 500 mbar pressure (Kelvin)
  - T850 – Temperature at 850 mbar pressure (Kelvin)
  - Wind – Surface wind speed (m/s)
  - BCSMASS – Black Carbon mass concentration at surface (μg/m3)
  - DUSMASS25 – Dust surface mass PM 2.5 concentration at surface (μg/m3)
  - OCSMASS – Organic carbon mass concentration at surface (μg/m3)
  - SO2SMASS – Sulphur dioxide mass concentration at surface (μg/m3)
  - SO4SMASS – Sulphate aerosol mass concentration at surface (μg/m3)
  - SSSMASS25 – Sea Salt surface mass concentration PM 2.5 (μg/m3)
  - TOTEXTTAU – Total aerosol extinction AOT @ 550 nm (unitless)
  - UTC_DATE – YearMonthDay (GMT date)
  - UTC_TIME – Time of sample (hours) (GMT time)

In [6]:
# Dataframe
columns = [
    "Lat",
    "Lon",
    "SRadius",
    "PS",
    "QV10m",
    "Q500",
    "Q850",
    "T10m",
    "T500",
    "T850",
    "WIND",
    "BCSMASS",
    "DUSMASS25",
    "OCSMASS",
    "SO2SMASS",
    "SO4SMASS",
    "SSSMASS25",
    "TOTEXTTAU",
    "UTC_DATE",
    "UTC_TIME"
]
df_merra2 = pd.concat(
    [pd.read_csv(
        ARGS["merra2_path"] + _, usecols=columns
    ) for _ in os.listdir(ARGS["merra2_path"])],
    ignore_index=True,
)
# df_merra2[-100:].to_csv("temp.json")

In [7]:
df_merra2.head()

,Lat,Lon,SRadius,PS,QV10m,Q500,Q850,T10m,T500,T850,WIND,BCSMASS,DUSMASS25,OCSMASS,SO2SMASS,SO4SMASS,SSSMASS25,TOTEXTTAU,UTC_DATE,UTC_TIME
0,9.0585,38.7616,6.6,76977.875,9.20574,3.88432,NaN,285.038,265.748,277.038,2.062,0.25398,2.21917,2.12822,0.76602,0.30719,0.38767,0.092,20180922,0.5
1,9.0585,38.7616,6.6,77014.508,9.25538,3.66306,NaN,284.934,265.555,276.934,1.970,0.25898,2.12003,2.17642,0.78171,0.30403,0.39381,0.091,20180922,1.5
2,9.0585,38.7616,6.6,77052.656,9.27073,3.38936,NaN,284.810,265.606,276.810,1.924,0.26466,2.02817,2.22190,0.79444,0.29636,0.39802,0.086,20180922,2.5
3,9.0585,38.7616,6.6,77089.477,9.30902,3.02982,NaN,284.701,265.937,276.701,1.776,0.27501,1.94905,2.30284,0.82014,0.28878,0.40029,0.081,20180922,3.5
4,9.0585,38.7616,6.6,77125.766,9.75173,2.68936,NaN,286.104,266.421,278.104,2.060,0.23931,1.79671,2.05182,0.67871,0.26947,0.39836,0.079,20180922,4.5

__Reference_Monitor_Data__:

- contains historical measurements of ground pollutants at each of the 22 locations for various time periods between 2016 and 2019. Each file contains measurements of PM2.5, PM10, and trace gas pollutants for time periods and sampling intervals that vary by site. Not all sites have all data for the full period.

In [8]:
# Dataframe
columns = ["date", "unit", "parameter", "value", "averagingperiod", "coordinates"]
# df_rmd = pd.concat(
#     [pd.read_csv(
#         ARGS["rmd_path"] + _,
#         usecols=columns
#     ) for _ in os.listdir(ARGS["rmd_path"])],
#     ignore_index=True
# )

df_rmd = pd.read_csv(
    "dataset/extract/Reference_Monitor_Data/LosAngeles.csv",
    usecols=columns,
)

coordinates = df_rmd['coordinates']
lat = [float(x.split(",")[0][10:]) for x in coordinates]
lon = [float(x.split(",")[1][11:-1]) for x in coordinates]

datetime = df_rmd['date']
date = [x[5:15].replace("-","") for x in datetime]
time = [x[16:24].replace(":","") for x in datetime]
gmt = [x[-7:-1] for x in datetime]

df_rmd['Lat'] = lat
df_rmd['Long'] = lon
df_rmd['date'] = date
df_rmd['time'] = time
df_rmd['gmt'] = gmt
df_rmd = df_rmd.drop(["coordinates"], axis=1)
# df_rmd["unit"].unique()

In [9]:
df_rmd.head()

,date,parameter,value,unit,averagingperiod,Lat,Long,time,gmt
0,20170811,co,0.340,ppm,"{unit=hours, value=1.0}",34.136475,-117.923965,000000,-08:00
1,20170811,no2,0.015,ppm,"{unit=hours, value=1.0}",34.136475,-117.923965,000000,-08:00
2,20170811,o3,0.061,ppm,"{unit=hours, value=1.0}",34.136475,-117.923965,000000,-08:00
3,20170811,co,0.240,ppm,"{unit=hours, value=1.0}",34.143900,-117.850800,000000,-08:00
4,20170811,no2,0.012,ppm,"{unit=hours, value=1.0}",34.143900,-117.850800,000000,-08:00

In [10]:
df_rmd.shape

(986034, 9)

In [12]:
df_rmd[df_rmd["value"] < 0.0]

,date,parameter,value,unit,averagingperiod,Lat,Long,time,gmt
933,20170901,pm25,-3.700,µg/m³,"{unit=hours, value=1.0}",34.14390,-117.85080,020000,-08:00
1643,20170925,so2,-0.001,ppm,"{unit=hours, value=1.0}",34.06643,-118.22675,230000,-08:00
1669,20170925,pm25,-3.600,µg/m³,"{unit=hours, value=1.0}",34.38330,-118.52830,230000,-08:00
1672,20170925,pm25,-0.100,µg/m³,"{unit=hours, value=1.0}",34.66959,-118.13069,230000,-08:00
2664,20170821,pm25,-3.000,µg/m³,"{unit=hours, value=1.0}",34.14390,-117.85080,020000,-08:00
...,...,...,...,...,...,...,...,...,...
984976,20190925,pm25,-1.000,µg/m³,"{unit=hours, value=1.0}",34.66959,-118.13069,200000,-08:00
985093,20190909,o3,-0.002,ppm,"{unit=hours, value=1.0}",33.92506,-117.95258,130000,-08:00
985621,20190217,pm25,-1.500,µg/m³,"{unit=hours, value=1.0}",34.38330,-118.52830,170000,-08:00
985726,20190217,pm25,-1.000,µg/m³,"{unit=hours, value=1.0}",34.66959,-118.13069,130000,-08:00
985884,20190217,pm25,-1.000,µg/m³,"{unit=hours, value=1.0}",34.66959,-118.13069,210000,-08:00

__AirQualitySystem__:

- data for all criteria and toxic pollutants (acute health effects and cancer causing, respectively) for the Los Angeles monitor sites for 2008-2018. There are 2.8 million individual samples in the file.

Field Position 	Field Name 	Description

1 | State Code | The FIPS code of the state in which the monitor resides.

2 | County Code | The FIPS code of the county in which the monitor resides.

3 | Site Num | A unique number within the county identifying the site.

4 | Parameter Code | The AQS code corresponding to the parameter measured by the monitor.

5 | POC | This is the “Parameter Occurrence Code” used to distinguish different instruments that measure the same parameter at the same site.

6 | Latitude | The monitoring site’s angular distance north of the equator measured in decimal degrees.

7 | Longitude | The monitoring site’s angular distance east of the prime meridian measured in decimal degrees.

8 | Datum | The Datum associated with the Latitude and Longitude measures.

9 | Parameter Name | The name or description assigned in AQS to the parameter measured by the monitor. Parameters may be pollutants or non-pollutants.

10 | Date Local | The calendar date of the sample in Local Standard Time at the monitor.

11 | Time Local | The time of day that sampling began on a 24-hour clock in Local Standard Time.

12 | Date GMT | The calendar date of the sample in Greenwich Mean Time.

13 | Time GMT | The time of day that sampling began on a 24-hour clock in Greenwich Mean Time.

14 | Sample Measurement | The measured value in the standard units of measure for the parameter.

15 | Units of Measure | The unit of measure for the parameter. QAD always returns data in the standard units for the parameter. Submitters are allowed to report data in any unit and EPA converts to a standard unit so that we may use the data in calculations.

16 | MDL | The Method Detection Limit. The minimum sample concentration detectable for the monitor and method. Note: if samples are reported below this level, they may have been replaced by 1/2 the MDL.

17 | Uncertainty | The total measurement uncertainty associated with a reported measurement as indicated by the reporting agency.

18 | Qualifier | Sample values may have qualifiers that indicate why they are missing or that they are out of the ordinary. Types of qualifiers are: null data, exceptional event, natural events, and quality assurance. The highest ranking qualifier, if any, is described in this field.

19 | Method Type | An indication of whether the method used to collect the data is a federal reference method (FRM), equivalent to a federal reference method, an approved regional method, or none of the above (non-federal reference method).

20 | Method Code | An internal system code indicating the method (processes, equipment, and protocols) used in gathering and measuring the sample. The method name is in the next column.

21 | Method Name | A short description of the processes, equipment, and protocols used in gathering and measuring the sample.

22 | State Name | The name of the state where the monitoring site is located.

23 | County Name | The name of the county where the monitoring site is located.

24 | Date of Last Change
	

The date the last time any numeric values in this record were updated in the AQS data system.

_These files contain the hourly data (sometimes called measurements, samples, etc). These files are separated by parameter (or parameter group) to make the sizes more manageable.
EPA does get sample data reported at durations other than hourly. For example, some SO2 is reported as 5-minute samples and some toxic substances are reported as 3-hour samples (and most PM speciation data is reported as 24-hour samples). These samples have not been included in these hourly files but their aggregates are included in the daily files, and the sample data is available on request.
If a particular file is empty (record count = 0) that means that no hourly data was collected for that parameter or group.
To keep the size of the raw data files smaller, less geographic descriptive information has been included. If you need the Local Site Name, CBSA, etc. you can find that in the Annual Summary file for the same monitor._

In [ ]:
# Dataframe
columns = [
    "Latitude",
    "Longitude",
    "Parameter Name",
    "Date Local",
    "Time Local",
    "Date GMT",
    "Time GMT",
    "Sample Measurement",
    "Unit of Measure"
]
df_aqs = pd.read_csv(
    ARGS["aqs_path"],
    usecols=columns
)
df_aqs.head()

In [ ]:
df